import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'home/home', // or whatever your intro document is
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'OPA Backend',
      link: {
        type: 'doc',
        id: 'opa-backend/introduction',
      },
      items: [
        'opa-backend/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'OPA Service',
      link: {
        type: 'doc',
        id: 'opa-service/introduction',
      },
      items: ['opa-service/opa-node-service'],
    },
    {
      type: 'category',
      label: 'OPA Authorization React',
      link: {
        type: 'doc',
        id: 'opa-authz-react/introduction',
      },
      items: [
      ],
    },
    {
      type: 'category',
      label: 'OPA Entity Checker',
      link: {
        type: 'doc',
        id: 'opa-entity-checker/introduction',
      },
      items: [
        'opa-entity-checker/quick-start',
        'opa-entity-checker/local-development',
        'opa-entity-checker/example-entity-checker-policy',
      ],
    },
    {
      type: 'category',
      label: 'OPA Entity Checker Processor',
      link: {
        type: 'doc',
        id: 'opa-entity-checker-processor/introduction',
      },
      items: ['opa-entity-checker-processor/quick-start'],
    },
    {
      type: 'category',
      label: 'OPA Permissions Wrapper Module',
      link: {
        type: 'doc',
        id: 'opa-permissions-wrapper-module/introduction',
      },
      items: [
        'opa-permissions-wrapper-module/quick-start',
        'opa-permissions-wrapper-module/architecture',
        'opa-permissions-wrapper-module/local-development',
        'opa-permissions-wrapper-module/inputs-and-outputs',
        'opa-permissions-wrapper-module/catalog-rules',
        'opa-permissions-wrapper-module/scaffolder-rules',
        'opa-permissions-wrapper-module/example-rbac-policy',
      ],
    },
    {
      type: 'category',
      label: 'OPA Policies',
      link: {
        type: 'doc',
        id: 'opa-policies/introduction',
      },
      items: ['opa-policies/quick-start'],
    },
    {
      type: 'category',
      label: 'Deploying OPA',
      items: ['deploying-opa/deploying-opa'],
    },
    {
      type: 'doc',
      id: 'CONTRIBUTING',
      label: 'Contributing',
    },
    {
      type: 'doc',
      id: 'ADOPTERS',
      label: 'Adopters',
    },
  ],
};

export default sidebars;
