theme: jekyll-theme-minimal
title: Backstage OPA Plugins!
description: Documentation for the OPA plugins for Backstage
baseurl: "/backstage-opa-plugins"
url: "https://yourusername.github.io"

author:
  name: Peter Macdonald

github_username:  parsifal-m

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/docs/"
  - title: "OPA Permissions Wrapper"
    url: "/plugins/opa-permissions-wrapper/"
  - title: "Example Policies"
    url: "/docs/example-policies/"

seo:
  type: Documentation
  name: Backstage OPA Plugins!
  description: "Documentation for the OPA plugins for Backstage"
  url: "https://parsifal-m.github.io/backstage-opa-plugins"