name: Lint and Format

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint and Format on Node.js 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint and Check Formatting
        run: |
          yarn lint:all
          yarn prettier:check

      - name: TypeScript Type Check
        run: yarn tsc:full

      - name: Quality Check Summary
        if: always()
        run: |
          echo "## Code Quality Results ✨" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Linting passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Formatting verified" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ TypeScript compilation passed" >> $GITHUB_STEP_SUMMARY
