name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Node 18
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Clean Yarn Cache
        run: yarn cache clean

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: yarn-${{ runner.OS }}-18-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-18-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: TypeScript Type Check
        run: yarn tsc:full

      - name: Run Tests
        run: yarn test:all --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}