name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Test on Node.js 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: TypeScript Type Check
        run: yarn tsc:full

      - name: Run Tests
        run: yarn test:silent

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Parsifal-M/backstage-opa-plugins

      - name: Test Summary
        if: always()
        run: |
          echo "## Test Results 🧪" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ TypeScript compilation passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ All tests executed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Coverage report uploaded" >> $GITHUB_STEP_SUMMARY
